---
title: "Lecture 12: Convergence in distribution"
author: "Ciaran Evans"
output: beamer_presentation
---

## Logistics

* Reminder: Exam 1 released February 21 (covers HW 1--4)

\bigskip

* Early-semester feedback form sent out

## Recap: Convergence in probability

**Definition:** A sequence of random variables $X_1, X_2,...$ *converges in probability* to a random variable $X$ if, for every $\varepsilon > 0$,
$$\lim \limits_{n \to \infty} P(|X_n - X| \geq \varepsilon) = 0$$
We write $X_n \overset{p}{\to} X$.

## Example

Suppose that $X_1, X_2, ... \overset{iid}{\sim} Uniform(0, 1)$, and let $X_{(n)} = \max\{X_1,...,X_n\}$. Then $X_{(n)} \overset{p}{\to} 1$.

\vspace{6cm}

## Convergence in distribution

**Definition:** A sequence of random variables $X_1, X_2,...$ *converges in distribution* to a random variable $X$ if

$$\lim \limits_{n \to \infty} F_{X_n}(x) = F_X(x)$$
at all points where $F_X(x)$ is continuous. We write $X_n \overset{d}{\to} X$.

\vspace{4cm}

## Example

Suppose that $X_1, X_2,... \overset{iid}{\sim} Uniform(0, 1)$. Let $X_{(n)} = \max\{X_1,...,X_n\}$. Then $n(1 - X_{(n)}) \overset{d}{\to} Y$, where $Y \sim Exp(1)$. 

\vspace{6cm}

## Convergence in distribution: Central Limit Theorem

Let $X_1, X_2,...$ be iid random variables, whose mgf exists in a neighborhood of 0. Let $\mu = \mathbb{E}[X_i]$ and $\sigma^2 = Var(X_i) < \infty$. Then 

$$\frac{\sqrt{n}(\bar{X}_n - \mu)}{\sigma} \overset{d}{\to} Z$$

where $Z \sim N(0, 1)$.

\vspace{4cm}

## Activity

Simulations to explore convergence in distribution:

[https://sta711-s25.github.io/class_activities/ca_lecture_12.html](https://sta711-s25.github.io/class_activities/ca_lecture_12.html)
