---
title: "Class Activity Solutions"
format: 
  html:
    embed-resources: true
editor: source
author: "Ciaran Evans"
---

1.

```{r}
set.seed(23)

n <- 20
nsim <- 1000
means <- rep(NA, nsim)

for(j in 1:nsim){
  x <- runif(n)
  means[j] <- mean(x)
}

mean(abs(means - 0.5) > 0.03)
```

With $n =20$, the sample mean $\overline{X}$ is at least 0.03 away from the true mean 0.5 about 65% of the time.


2.

```{r}
set.seed(23)

ns <- c(10, 20, 50, 100, 200, 500)
res <- rep(NA, length(ns))
nsim <- 1000

for(i in 1:length(ns)){
  n <- ns[i]
  means <- rep(NA, nsim)

  for(j in 1:nsim){
    x <- runif(n)
    means[j] <- mean(x)
  }
  
  res[i] <- mean(abs(means - 0.5) > 0.03)
}

plot(ns, res, xlab = "Sample size (n)", ylab = "P(|Xbar - 0.5| > 0.03)",
     pch = 16)
```


3.

```{r}
set.seed(23)

ns <- c(10, 20, 50, 100, 200, 500)
res <- rep(NA, length(ns))
nsim <- 1000
epsilon <- 0.03

for(i in 1:length(ns)){
  n <- ns[i]
  maxes <- rep(NA, nsim)

  for(j in 1:nsim){
    x <- runif(n)
    maxes[j] <- max(x)
  }
  
  res[i] <- mean(abs(maxes - 1) > epsilon)
}

plot(ns, res, xlab = "Sample size (n)", 
     ylab = "P(|X(n) - 1| > epsilon)", pch=16)
```



